image: alpine/latest
packages:
  - alsa-lib-dev
  - libx11-dev
  - libxcursor-dev
  - libxinerama-dev
  - libxi-dev
  - libxrandr-dev
  - mesa-dev
  - pkgconf
  - go
sources:
  - https://github.com/hajimehoshi/ebiten#{{.Commit}}
tasks:
  - build: |
      cd ebiten
      go build -tags=example ./...
