package stances

import (
	"math"

	"rbrewer.com/core"
)

var (
	RestRight1 core.Stance = core.Stance{
		RightUpperArm: -math.Pi / 16,
		LeftUpperArm:  math.Pi / 16,
		Direction:     core.RIGHT,
		RightUpperLeg: 0,
		LeftUpperLeg:  0,
		Head:          0,
		Torso:         0,
		RightLowerArm: 0,
		RightLowerLeg: 0,
		RightFoot:     0,
		LeftLowerArm:  0,
		LeftLowerLeg:  0,
		LeftFoot:      0,
		Weapon:        0,
	}
	RestRight2 core.Stance = core.Stance{
		RightUpperArm: -math.Pi / 20,
		LeftUpperArm:  math.Pi / 20,
		Direction:     core.RIGHT,
		RightUpperLeg: 0,
		LeftUpperLeg:  0,
		Head:          0,
		Torso:         0,
		RightLowerArm: 0,
		RightLowerLeg: 0,
		RightFoot:     0,
		LeftLowerArm:  0,
		LeftLowerLeg:  0,
		LeftFoot:      0,
		Weapon:        0,
	}
	RestLeft1 core.Stance = core.Stance{
		RightUpperArm: -math.Pi / 16,
		LeftUpperArm:  math.Pi / 16,
		Direction:     core.LEFT,
		RightUpperLeg: 0,
		LeftUpperLeg:  0,
		Head:          0,
		Torso:         0,
		RightLowerArm: 0,
		RightLowerLeg: 0,
		RightFoot:     0,
		LeftLowerArm:  0,
		LeftLowerLeg:  0,
		LeftFoot:      0,
		Weapon:        0,
	}
	RestLeft2 core.Stance = core.Stance{
		RightUpperArm: -math.Pi / 20,
		LeftUpperArm:  math.Pi / 20,
		Direction:     core.LEFT,
		RightUpperLeg: 0,
		LeftUpperLeg:  0,
		Head:          0,
		Torso:         0,
		RightLowerArm: 0,
		RightLowerLeg: 0,
		RightFoot:     0,
		LeftLowerArm:  0,
		LeftLowerLeg:  0,
		LeftFoot:      0,
		Weapon:        0,
	}
	WalkRight1 core.Stance = core.Stance{
		RightUpperArm: math.Pi / 6,
		LeftUpperArm:  -math.Pi / 6,
		RightUpperLeg: -math.Pi / 6,
		LeftUpperLeg:  math.Pi / 6,
		Direction:     core.RIGHT,
		Head:          0,
		Torso:         0,
		RightLowerArm: -math.Pi / 20,
		RightLowerLeg: math.Pi / 20,
		RightFoot:     0,
		LeftLowerArm:  -math.Pi / 20,
		LeftLowerLeg:  0,
		LeftFoot:      0,
		Weapon:        0,
	}
	WalkRight2 core.Stance = core.Stance{
		RightUpperArm: -math.Pi / 6,
		LeftUpperArm:  math.Pi / 6,
		RightUpperLeg: math.Pi / 6,
		LeftUpperLeg:  -math.Pi / 6,
		Direction:     core.RIGHT,
		Head:          0,
		Torso:         0,
		RightLowerArm: -math.Pi / 20,
		RightLowerLeg: 0,
		RightFoot:     0,
		LeftLowerArm:  -math.Pi / 20,
		LeftLowerLeg:  math.Pi / 20,
		LeftFoot:      0,
		Weapon:        0,
	}
	WalkLeft1 core.Stance = core.Stance{
		RightUpperArm: math.Pi / 6,
		LeftUpperArm:  -math.Pi / 6,
		RightUpperLeg: -math.Pi / 6,
		LeftUpperLeg:  math.Pi / 6,
		Direction:     core.LEFT,
		Head:          0,
		Torso:         0,
		RightLowerArm: math.Pi / 20,
		RightLowerLeg: -math.Pi / 20,
		RightFoot:     0,
		LeftLowerArm:  math.Pi / 20,
		LeftLowerLeg:  0,
		LeftFoot:      0,
		Weapon:        0,
	}
	WalkLeft2 core.Stance = core.Stance{
		RightUpperArm: -math.Pi / 6,
		LeftUpperArm:  math.Pi / 6,
		RightUpperLeg: math.Pi / 6,
		LeftUpperLeg:  -math.Pi / 6,
		Direction:     core.LEFT,
		Head:          0,
		Torso:         0,
		RightLowerArm: math.Pi / 20,
		RightLowerLeg: 0,
		RightFoot:     0,
		LeftLowerArm:  math.Pi / 20,
		LeftLowerLeg:  -math.Pi / 20,
		LeftFoot:      0,
		Weapon:        0,
	}
	JumpRight1 core.Stance = core.Stance{
		RightUpperArm: math.Pi / 20,
		LeftUpperArm:  math.Pi / 8,
		RightUpperLeg: -math.Pi / 4,
		LeftUpperLeg:  -math.Pi / 4,
		Direction:     core.RIGHT,
		Head:          0,
		Torso:         math.Pi / 10,
		RightLowerArm: -math.Pi / 3,
		RightLowerLeg: math.Pi / 6,
		RightFoot:     0,
		LeftLowerArm:  -math.Pi / 3,
		LeftLowerLeg:  math.Pi / 6,
		LeftFoot:      0,
		Weapon:        0,
	}
	JumpRight2 core.Stance = core.Stance{
		RightUpperArm: -math.Pi / 10,
		LeftUpperArm:  math.Pi / 5,
		RightUpperLeg: -math.Pi / 10,
		LeftUpperLeg:  -math.Pi / 15,
		Direction:     core.RIGHT,
		Head:          0,
		Torso:         0,
		RightLowerArm: -math.Pi / 5,
		RightLowerLeg: math.Pi / 5,
		RightFoot:     0,
		LeftLowerArm:  -math.Pi / 5,
		LeftLowerLeg:  math.Pi / 5,
		LeftFoot:      0,
		Weapon:        0,
	}
	JumpRight3 core.Stance = core.Stance{
		RightUpperArm: math.Pi / 20,
		LeftUpperArm:  math.Pi / 8,
		RightUpperLeg: -math.Pi / 4,
		LeftUpperLeg:  -math.Pi / 4,
		Direction:     core.RIGHT,
		Head:          math.Pi / 20,
		Torso:         math.Pi / 10,
		RightLowerArm: -math.Pi / 3,
		RightLowerLeg: math.Pi / 6,
		RightFoot:     0,
		LeftLowerArm:  -math.Pi / 3,
		LeftLowerLeg:  math.Pi / 6,
		LeftFoot:      0,
		Weapon:        0,
	}
	JumpLeft1 core.Stance = core.Stance{
		RightUpperArm: math.Pi / 20,
		LeftUpperArm:  math.Pi / 8,
		RightUpperLeg: math.Pi / 4,
		LeftUpperLeg:  math.Pi / 4,
		Direction:     core.LEFT,
		Head:          0,
		Torso:         -math.Pi / 10,
		RightLowerArm: math.Pi / 3,
		RightLowerLeg: -math.Pi / 6,
		RightFoot:     0,
		LeftLowerArm:  math.Pi / 3,
		LeftLowerLeg:  -math.Pi / 6,
		LeftFoot:      0,
		Weapon:        0,
	}
	JumpLeft2 core.Stance = core.Stance{
		RightUpperArm: -math.Pi / 10,
		LeftUpperArm:  math.Pi / 5,
		RightUpperLeg: math.Pi / 10,
		LeftUpperLeg:  math.Pi / 15,
		Direction:     core.LEFT,
		Head:          0,
		Torso:         0,
		RightLowerArm: math.Pi / 5,
		RightLowerLeg: -math.Pi / 5,
		RightFoot:     0,
		LeftLowerArm:  math.Pi / 5,
		LeftLowerLeg:  -math.Pi / 5,
		LeftFoot:      0,
		Weapon:        0,
	}
	JumpLeft3 core.Stance = core.Stance{
		RightUpperArm: math.Pi / 20,
		LeftUpperArm:  math.Pi / 8,
		RightUpperLeg: math.Pi / 4,
		LeftUpperLeg:  math.Pi / 4,
		Direction:     core.LEFT,
		Head:          -math.Pi / 20,
		Torso:         -math.Pi / 10,
		RightLowerArm: math.Pi / 3,
		RightLowerLeg: -math.Pi / 6,
		RightFoot:     0,
		LeftLowerArm:  math.Pi / 3,
		LeftLowerLeg:  -math.Pi / 6,
		LeftFoot:      0,
		Weapon:        0,
	}
	LeapRight core.Stance = core.Stance{
		RightUpperArm: -math.Pi / 3,
		LeftUpperArm:  math.Pi / 3,
		LeftUpperLeg:  -math.Pi / 2,
		RightUpperLeg: math.Pi / 4,
		Direction:     core.RIGHT,
		Head:          0,
		Torso:         0,
		RightLowerArm: -math.Pi / 3,
		LeftLowerLeg:  math.Pi / 6,
		RightFoot:     0,
		LeftLowerArm:  -math.Pi / 3,
		RightLowerLeg: math.Pi / 6,
		LeftFoot:      0,
		Weapon:        0,
	}
	LeapLeft core.Stance = core.Stance{
		RightUpperArm: -math.Pi / 3,
		LeftUpperArm:  math.Pi / 3,
		LeftUpperLeg:  math.Pi / 2,
		RightUpperLeg: -math.Pi / 4,
		Direction:     core.LEFT,
		Head:          0,
		Torso:         0,
		RightLowerArm: math.Pi / 3,
		LeftLowerLeg:  -math.Pi / 6,
		RightFoot:     0,
		LeftLowerArm:  math.Pi / 3,
		RightLowerLeg: -math.Pi / 6,
		LeftFoot:      0,
		Weapon:        0,
	}
)
